name: Checks
on: [push, pull_request, workflow_dispatch]
jobs:
  core:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - run: cargo fmt --check
      - run: cargo test --locked --no-default-features
      - run: cargo clippy --locked --no-default-features --all-targets -- -D warnings
